name: Deploy ignite-ReactJS

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      if:
        steps.cache-node_modules.outputs.cache-hit != 'true'
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  Deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Organize files
      run: |
        mkdir ignite-reactjs
        mv dist/index.html ignite-reactjs/index.html

    - name: SSH-Deploy
      if: success()
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        TARGET: ${{ secrets.SSH_REMOTE_TARGET }}
        EXCLUDE: "/node_modules/"
